HTML_header_Build = """<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><META http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body>\r\n\r\n<!---- HLX Report Generated by sergio@hlx.co | http://hlx.co ----!>\r\n\r\n<table border="1" width="90%" align="center" cellpadding="5" cellspacing="1">"""


HTML_header_Build_Fancy = """
			<!DOCTYPE html>
				<html lang="en" >
				<head>
				  <meta charset="UTF-8">
				  <title>Console</title>
				  <link rel="stylesheet" href="http://hlx.sh/static_assets/lpb/template/css/warehouse_dashboard_style.css">

				</head>
				<body>
				<!-- partial:index.partial.html -->
				<html lang="en">
				<head>
					<meta charset="utf-8" />
					<title>Console</title>
					<meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
				</head>

				<body>
				<table class="table-fill">
				"""

HTML_header_Build_Responstable = """

			<!DOCTYPE html>
			<html lang="en" >
			<head>
			<meta charset="UTF-8">
			<title>Responstable 2.0: a responsive table solution</title>
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
			<link rel="stylesheet" href="http://hlx.sh/static_assets/lpb/template/css/warehouse_dashboard_responstable_style.css">

			</head>
			<body>

			<table class="responstable">

				"""

"""
<script>
$(document).ready(function() {
    $('#tablelinks').DataTable();
} );
</script>
"""

header_writeToHTMLMulti = """
				<!DOCTYPE html>
				<html>
				<head>

				<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
				<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap.min.css">
				<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
				<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
				<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap.min.js"></script>
						
				<meta name="viewport" content="width=device-width, initial-scale=1">
				
				<style>
				body {font-family: Arial;}

				/* Style the tab */
				.tab {
				overflow: hidden;
				border: 1px solid #ccc;
				background-color: #f1f1f1;
				}

				/* Style the buttons inside the tab */
				.tab button {
				background-color: inherit;
				float: left;
				border: none;
				outline: none;
				cursor: pointer;
				padding: 14px 16px;
				transition: 0.3s;
				font-size: 17px;
				}

				/* Change background color of buttons on hover */
				.tab button:hover {
				background-color: #ddd;
				}

				/* Create an active/current tablink class */
				.tab button.active {
				background-color: #ccc;
				}

				/* Style the tab content */
				.tabcontent1 {
				display: block;
				padding: 6px 12px;
				border: 1px solid #ccc;
				border-top: none;
				}

				.tabcontent {
				display: none;
				padding: 6px 12px;
				border: 1px solid #ccc;
				border-top: none;
				}
				</style>
				</head>
				<body>

				<div class="tab">

				"""

jsScript_writeToHTMLMulti =  """
				<script>
				function openCity(evt, cityName) {

				$(".test1").removeClass("tabcontent1");
				$(".test1").addClass("tabcontent");

				var i, tabcontent, tablinks;
				tabcontent = document.getElementsByClassName("tabcontent");
				for (i = 0; i < tabcontent.length; i++) {
					tabcontent[i].style.display = "none";
				}
				tablinks = document.getElementsByClassName("tablinks");
				for (i = 0; i < tablinks.length; i++) {
					tablinks[i].className = tablinks[i].className.replace(" active", "");
				}
				document.getElementById(cityName).style.display = "block";
				evt.currentTarget.className += " active";
				}

				</script>
				
				</body>
				</html>

			"""