header = """
			<!DOCTYPE html>
				<html>
				<head>
				<meta name="viewport" content="width=device-width, initial-scale=1">
				<style>
				body {font-family: Arial;}

				/* Style the tab */
				.tab {
				overflow: hidden;
				border: 1px solid #ccc;
				background-color: #f1f1f1;
				}

				/* Style the buttons inside the tab */
				.tab button {
				background-color: inherit;
				float: left;
				border: none;
				outline: none;
				cursor: pointer;
				padding: 14px 16px;
				transition: 0.3s;
				font-size: 17px;
				}

				/* Change background color of buttons on hover */
				.tab button:hover {
				background-color: #ddd;
				}

				/* Create an active/current tablink class */
				.tab button.active {
				background-color: #ccc;
				}

				/* Style the tab content */
				.tabcontent {
				display: none;
				padding: 6px 12px;
				border: 1px solid #ccc;
				border-top: none;
				}
				</style>
				</head>
				<body>

				<h2>Tabs</h2>
				<p>Click on the buttons inside the tabbed menu:</p>

				<div class="tab">
			"""


htmltemplate =  """
				
				<button class="tablinks" onclick="openCity(event,'Sheet name')">Sheet name</button>
				</div>
		

				<div id="Sheet name" class="tabcontent">
				<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><META http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body><!---- HLX Report Generated by sergio@hlx.co | http://hlx.co ----!><table border="1" width="90%" align="center" cellpadding="5" cellspacing="1"><thead><th bgcolor="Yellow"><font size="2" face="verdana"><B>Company Name</b><font></th><th bgcolor="Yellow"><font size="2" face="verdana"><B>Buyer</b><font></th><th bgcolor="Yellow"><font size="2" face="verdana"><B>ProductID</b><font></th></thead><tbody><tr bgcolor="#ffffff"><td><font size="2" face="verdana">My Company</font></td><td><font size="2" face="verdana">Unknown</font></td><td><font size="2" face="verdana">POOROY2N4KIT</font></td><tr bgcolor="#e6e6e6"><td><font size="2" face="verdana">My Company1</font></td><td><font size="2" face="verdana">Unknown1</font></td><td><font size="2" face="verdana">POOROY2N4KIT1111</font></td><tr bgcolor="#ffffff"><td><font size="2" face="verdana">My Company2</font></td><td><font size="2" face="verdana">Unknown2</font></td><td><font size="2" face="verdana">POOROY2N4KIT2222</font></td></tr></tbody></table></body></html>

				</div>


				"""
















jsScript =  """
				<script>
				function openCity(evt, cityName) {
				var i, tabcontent, tablinks;
				tabcontent = document.getElementsByClassName("tabcontent");
				for (i = 0; i < tabcontent.length; i++) {
					tabcontent[i].style.display = "none";
				}
				tablinks = document.getElementsByClassName("tablinks");
				for (i = 0; i < tablinks.length; i++) {
					tablinks[i].className = tablinks[i].className.replace(" active", "");
				}
				document.getElementById(cityName).style.display = "block";
				evt.currentTarget.className += " active";
				}
				</script>
				
				</body>
				</html> 
			"""

content = header + htmltemplate + jsScript

with open("Content.html","w") as f:
	f.write(content)